/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpSliderSl1 {
        /**
          * @default 'Go to slide'
         */
        "bulletBtnAria": string;
        /**
          * @default true
         */
        "isPreviousNextNavigation": boolean;
        /**
          * @default true
         */
        "isSlideBullet": boolean;
        "itemToShow": number;
        /**
          * @default 'Next slide'
         */
        "nextBtnAria": string;
        /**
          * @default 'Previous slide'
         */
        "previousBtnAria": string;
        /**
          * @default 30
         */
        "slideGap": number;
        /**
          * @default 'Carousel Slider'
         */
        "slideTitleAria": string;
    }
}
declare global {
    interface HTMLIpSliderSl1Element extends Components.IpSliderSl1, HTMLStencilElement {
    }
    var HTMLIpSliderSl1Element: {
        prototype: HTMLIpSliderSl1Element;
        new (): HTMLIpSliderSl1Element;
    };
    interface HTMLElementTagNameMap {
        "ip-slider-sl-1": HTMLIpSliderSl1Element;
    }
}
declare namespace LocalJSX {
    interface IpSliderSl1 {
        /**
          * @default 'Go to slide'
         */
        "bulletBtnAria"?: string;
        /**
          * @default true
         */
        "isPreviousNextNavigation"?: boolean;
        /**
          * @default true
         */
        "isSlideBullet"?: boolean;
        "itemToShow"?: number;
        /**
          * @default 'Next slide'
         */
        "nextBtnAria"?: string;
        /**
          * @default 'Previous slide'
         */
        "previousBtnAria"?: string;
        /**
          * @default 30
         */
        "slideGap"?: number;
        /**
          * @default 'Carousel Slider'
         */
        "slideTitleAria"?: string;
    }
    interface IntrinsicElements {
        "ip-slider-sl-1": IpSliderSl1;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-slider-sl-1": LocalJSX.IpSliderSl1 & JSXBase.HTMLAttributes<HTMLIpSliderSl1Element>;
        }
    }
}
