/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpAccordion {
        "accordionHeaders": accordionHeadersInterface[] | string;
        "isFirstPanelOpen": boolean;
        "isSingleOpen": boolean;
        /**
          * @default 'h2'
         */
        "titleTag": string;
    }
}
declare global {
    interface HTMLIpAccordionElement extends Components.IpAccordion, HTMLStencilElement {
    }
    var HTMLIpAccordionElement: {
        prototype: HTMLIpAccordionElement;
        new (): HTMLIpAccordionElement;
    };
    interface HTMLElementTagNameMap {
        "ip-accordion": HTMLIpAccordionElement;
    }
}
declare namespace LocalJSX {
    interface IpAccordion {
        "accordionHeaders"?: accordionHeadersInterface[] | string;
        "isFirstPanelOpen"?: boolean;
        "isSingleOpen"?: boolean;
        /**
          * @default 'h2'
         */
        "titleTag"?: string;
    }
    interface IntrinsicElements {
        "ip-accordion": IpAccordion;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-accordion": LocalJSX.IpAccordion & JSXBase.HTMLAttributes<HTMLIpAccordionElement>;
        }
    }
}
