/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpBreadcrumb {
        /**
          * @default '[]'
         */
        "breadcrumbItems": string;
        /**
          * @default ''
         */
        "breadcrumbTitle": string;
        /**
          * @default 'Link to'
         */
        "prefixAriaLabel": string;
        /**
          * @default '>'
         */
        "separatorIcon": string;
    }
}
declare global {
    interface HTMLIpBreadcrumbElement extends Components.IpBreadcrumb, HTMLStencilElement {
    }
    var HTMLIpBreadcrumbElement: {
        prototype: HTMLIpBreadcrumbElement;
        new (): HTMLIpBreadcrumbElement;
    };
    interface HTMLElementTagNameMap {
        "ip-breadcrumb": HTMLIpBreadcrumbElement;
    }
}
declare namespace LocalJSX {
    interface IpBreadcrumb {
        /**
          * @default '[]'
         */
        "breadcrumbItems"?: string;
        /**
          * @default ''
         */
        "breadcrumbTitle"?: string;
        /**
          * @default 'Link to'
         */
        "prefixAriaLabel"?: string;
        /**
          * @default '>'
         */
        "separatorIcon"?: string;
    }
    interface IntrinsicElements {
        "ip-breadcrumb": IpBreadcrumb;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-breadcrumb": LocalJSX.IpBreadcrumb & JSXBase.HTMLAttributes<HTMLIpBreadcrumbElement>;
        }
    }
}
