/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpShowMore {
        /**
          * @default 'Show Less'
         */
        "showLessText": string;
        /**
          * @default 'Show More'
         */
        "showMoreText": string;
        /**
          * @default 'white'
         */
        "svgColor": string;
    }
}
declare global {
    interface HTMLIpShowMoreElement extends Components.IpShowMore, HTMLStencilElement {
    }
    var HTMLIpShowMoreElement: {
        prototype: HTMLIpShowMoreElement;
        new (): HTMLIpShowMoreElement;
    };
    interface HTMLElementTagNameMap {
        "ip-show-more": HTMLIpShowMoreElement;
    }
}
declare namespace LocalJSX {
    interface IpShowMore {
        /**
          * @default 'Show Less'
         */
        "showLessText"?: string;
        /**
          * @default 'Show More'
         */
        "showMoreText"?: string;
        /**
          * @default 'white'
         */
        "svgColor"?: string;
    }
    interface IntrinsicElements {
        "ip-show-more": IpShowMore;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-show-more": LocalJSX.IpShowMore & JSXBase.HTMLAttributes<HTMLIpShowMoreElement>;
        }
    }
}
