/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpModal {
        /**
          * @default 'Open modal'
         */
        "buttonText": string;
        /**
          * @default 'Close the dialog'
         */
        "closeAriaLabel": string;
        /**
          * @default 'black'
         */
        "svgColor": string;
    }
}
declare global {
    interface HTMLIpModalElement extends Components.IpModal, HTMLStencilElement {
    }
    var HTMLIpModalElement: {
        prototype: HTMLIpModalElement;
        new (): HTMLIpModalElement;
    };
    interface HTMLElementTagNameMap {
        "ip-modal": HTMLIpModalElement;
    }
}
declare namespace LocalJSX {
    interface IpModal {
        /**
          * @default 'Open modal'
         */
        "buttonText"?: string;
        /**
          * @default 'Close the dialog'
         */
        "closeAriaLabel"?: string;
        /**
          * @default 'black'
         */
        "svgColor"?: string;
    }
    interface IntrinsicElements {
        "ip-modal": IpModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-modal": LocalJSX.IpModal & JSXBase.HTMLAttributes<HTMLIpModalElement>;
        }
    }
}
