/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpFootnote {
        /**
          * @default 'Back to main text'
         */
        "btnAriaLabel": string;
        /**
          * @default 'default-id'
         */
        "identifier": string;
        /**
          * @default 'grey'
         */
        "svgColor": string;
        "text": string;
    }
}
declare global {
    interface HTMLIpFootnoteElement extends Components.IpFootnote, HTMLStencilElement {
    }
    var HTMLIpFootnoteElement: {
        prototype: HTMLIpFootnoteElement;
        new (): HTMLIpFootnoteElement;
    };
    interface HTMLElementTagNameMap {
        "ip-footnote": HTMLIpFootnoteElement;
    }
}
declare namespace LocalJSX {
    interface IpFootnote {
        /**
          * @default 'Back to main text'
         */
        "btnAriaLabel"?: string;
        /**
          * @default 'default-id'
         */
        "identifier"?: string;
        /**
          * @default 'grey'
         */
        "svgColor"?: string;
        "text"?: string;
    }

    interface IpFootnoteAttributes {
        "identifier": string;
        "btnAriaLabel": string;
        "text": string;
        "svgColor": string;
    }

    interface IntrinsicElements {
        "ip-footnote": Omit<IpFootnote, keyof IpFootnoteAttributes> & { [K in keyof IpFootnote & keyof IpFootnoteAttributes]?: IpFootnote[K] } & { [K in keyof IpFootnote & keyof IpFootnoteAttributes as `attr:${K}`]?: IpFootnoteAttributes[K] } & { [K in keyof IpFootnote & keyof IpFootnoteAttributes as `prop:${K}`]?: IpFootnote[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-footnote": LocalJSX.IntrinsicElements["ip-footnote"] & JSXBase.HTMLAttributes<HTMLIpFootnoteElement>;
        }
    }
}
