/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MenuItem } from "./components/menu-1/burger-menu";
import { MenuItem as MenuItem1 } from "./components/menu-2/navigation-bar";
export { MenuItem } from "./components/menu-1/burger-menu";
export { MenuItem as MenuItem1 } from "./components/menu-2/navigation-bar";
export namespace Components {
    interface IpBurgerMenu {
        /**
          * @default 'Close menu'
         */
        "closeMenuAriaLabel": string;
        /**
          * @default []
         */
        "items": MenuItem[];
        "menuData": string;
        /**
          * @default 'Open menu'
         */
        "openMenuAriaLabel": string;
        /**
          * @default '../../assets/images/arrow-right.svg'
         */
        "pathToArrowRightIcon": string;
        /**
          * @default '../../assets/images/x-icon.svg'
         */
        "pathToCloseIcon": string;
        /**
          * @default '../../assets/images/icon-list.svg'
         */
        "pathToOpenIcon": string;
    }
    interface IpNavigationBar {
        /**
          * @default 'Close menu'
         */
        "closeMenuAriaLabel": string;
        /**
          * @default 'Close'
         */
        "closeSubmenuPrefix": string;
        /**
          * @default '[]'
         */
        "menuData": string;
        /**
          * @default []
         */
        "menuItems": MenuItem1[];
        /**
          * @default 'Open menu'
         */
        "openMenuAriaLabel": string;
        /**
          * @default 'Open'
         */
        "openSubmenuPrefix": string;
        /**
          * @default '../../assets/images/close-icon.svg'
         */
        "pathToCloseIcon": string;
        /**
          * @default '../../assets/images/open-icon.svg'
         */
        "pathToOpenIcon": string;
    }
}
declare global {
    interface HTMLIpBurgerMenuElement extends Components.IpBurgerMenu, HTMLStencilElement {
    }
    var HTMLIpBurgerMenuElement: {
        prototype: HTMLIpBurgerMenuElement;
        new (): HTMLIpBurgerMenuElement;
    };
    interface HTMLIpNavigationBarElement extends Components.IpNavigationBar, HTMLStencilElement {
    }
    var HTMLIpNavigationBarElement: {
        prototype: HTMLIpNavigationBarElement;
        new (): HTMLIpNavigationBarElement;
    };
    interface HTMLElementTagNameMap {
        "ip-burger-menu": HTMLIpBurgerMenuElement;
        "ip-navigation-bar": HTMLIpNavigationBarElement;
    }
}
declare namespace LocalJSX {
    interface IpBurgerMenu {
        /**
          * @default 'Close menu'
         */
        "closeMenuAriaLabel"?: string;
        /**
          * @default []
         */
        "items"?: MenuItem[];
        "menuData"?: string;
        /**
          * @default 'Open menu'
         */
        "openMenuAriaLabel"?: string;
        /**
          * @default '../../assets/images/arrow-right.svg'
         */
        "pathToArrowRightIcon"?: string;
        /**
          * @default '../../assets/images/x-icon.svg'
         */
        "pathToCloseIcon"?: string;
        /**
          * @default '../../assets/images/icon-list.svg'
         */
        "pathToOpenIcon"?: string;
    }
    interface IpNavigationBar {
        /**
          * @default 'Close menu'
         */
        "closeMenuAriaLabel"?: string;
        /**
          * @default 'Close'
         */
        "closeSubmenuPrefix"?: string;
        /**
          * @default '[]'
         */
        "menuData"?: string;
        /**
          * @default []
         */
        "menuItems"?: MenuItem1[];
        /**
          * @default 'Open menu'
         */
        "openMenuAriaLabel"?: string;
        /**
          * @default 'Open'
         */
        "openSubmenuPrefix"?: string;
        /**
          * @default '../../assets/images/close-icon.svg'
         */
        "pathToCloseIcon"?: string;
        /**
          * @default '../../assets/images/open-icon.svg'
         */
        "pathToOpenIcon"?: string;
    }
    interface IntrinsicElements {
        "ip-burger-menu": IpBurgerMenu;
        "ip-navigation-bar": IpNavigationBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-burger-menu": LocalJSX.IpBurgerMenu & JSXBase.HTMLAttributes<HTMLIpBurgerMenuElement>;
            "ip-navigation-bar": LocalJSX.IpNavigationBar & JSXBase.HTMLAttributes<HTMLIpNavigationBarElement>;
        }
    }
}
