/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpTabPanel {
        "selectedTab": string;
        "tabPanelHeaders": TabPanelInterface[] | string;
        "tabPanelTitle": string;
        "titleTag": string;
    }
}
declare global {
    interface HTMLIpTabPanelElement extends Components.IpTabPanel, HTMLStencilElement {
    }
    var HTMLIpTabPanelElement: {
        prototype: HTMLIpTabPanelElement;
        new (): HTMLIpTabPanelElement;
    };
    interface HTMLElementTagNameMap {
        "ip-tab-panel": HTMLIpTabPanelElement;
    }
}
declare namespace LocalJSX {
    interface IpTabPanel {
        "selectedTab"?: string;
        "tabPanelHeaders"?: TabPanelInterface[] | string;
        "tabPanelTitle"?: string;
        "titleTag"?: string;
    }

    interface IpTabPanelAttributes {
        "tabPanelHeaders": TabPanelInterface[] | string;
        "tabPanelTitle": string;
        "titleTag": string;
        "selectedTab": string;
    }

    interface IntrinsicElements {
        "ip-tab-panel": Omit<IpTabPanel, keyof IpTabPanelAttributes> & { [K in keyof IpTabPanel & keyof IpTabPanelAttributes]?: IpTabPanel[K] } & { [K in keyof IpTabPanel & keyof IpTabPanelAttributes as `attr:${K}`]?: IpTabPanelAttributes[K] } & { [K in keyof IpTabPanel & keyof IpTabPanelAttributes as `prop:${K}`]?: IpTabPanel[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-tab-panel": LocalJSX.IntrinsicElements["ip-tab-panel"] & JSXBase.HTMLAttributes<HTMLIpTabPanelElement>;
        }
    }
}
