/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IpTable {
        "columns": string;
        "rows": string;
    }
}
declare global {
    interface HTMLIpTableElement extends Components.IpTable, HTMLStencilElement {
    }
    var HTMLIpTableElement: {
        prototype: HTMLIpTableElement;
        new (): HTMLIpTableElement;
    };
    interface HTMLElementTagNameMap {
        "ip-table": HTMLIpTableElement;
    }
}
declare namespace LocalJSX {
    interface IpTable {
        "columns"?: string;
        "rows"?: string;
    }

    interface IpTableAttributes {
        "columns": string;
        "rows": string;
    }

    interface IntrinsicElements {
        "ip-table": Omit<IpTable, keyof IpTableAttributes> & { [K in keyof IpTable & keyof IpTableAttributes]?: IpTable[K] } & { [K in keyof IpTable & keyof IpTableAttributes as `attr:${K}`]?: IpTableAttributes[K] } & { [K in keyof IpTable & keyof IpTableAttributes as `prop:${K}`]?: IpTable[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-table": LocalJSX.IntrinsicElements["ip-table"] & JSXBase.HTMLAttributes<HTMLIpTableElement>;
        }
    }
}
